# Generated by Django 5.0 on 2023-12-30 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='title')),
                ('items', models.JSONField(default=dict, verbose_name='items')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='last modified at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='last modified at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets_created', to='profiles.profile', verbose_name='sheet by')),
            ],
            options={
                'ordering': ['last_modified_at'],
            },
        ),
    ]
