# Generated by Django 4.2.4 on 2023-08-16 12:29

from django.db import migrations
from core.settings import DEFAULT_SITE_DOMAIN, DEFAULT_SITE_NAME


def set_default_site(apps, schema_editor):
    """
    use historical version since we can't import the model
    directly as it may be a newer version than this
    migration expects

    https://docs.djangoproject.com/en/4.2/topics/migrations/#data-migrations
    """
    Site = apps.get_model("sites", "Site")

    try:
        current_site = Site.objects.get(id=1)
        current_site.domain = DEFAULT_SITE_DOMAIN
        current_site.name = DEFAULT_SITE_NAME
        current_site.save()
    except Site.DoesNotExist:
        Site.objects.create(domain=DEFAULT_SITE_DOMAIN,
                            name=DEFAULT_SITE_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique")
    ]

    operations = [
        migrations.RunPython(set_default_site)
    ]
