# Generated by Django 4.2.7 on 2023-12-03 05:17

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import users.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('verified_at', models.DateTimeField(null=True, verbose_name='date email veriried')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='last modified at')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-joined_at'],
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
